layout_spectrum: 0.5418904
color:
  saturation: 0.8752205
  lightness: 0.7062299
  brandStrength: 1
  brandColors:
    - '#282D27'
    - '#56636C'
    - '#697C8D'
    - '#879AAB'
    - '#C1CDCD'
  rhythmicContrast: 0.4615809
typography_spectrum: 0.9221267
name: Andrewfierce
